
<FORM ACTION="/dcc-terminos-footer/index" METHOD="POST"> 
	 
		  
        
        <?php echo $this->formLabel('id','id');?>
        <?php echo $this->formText('id',$this->data->getId(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('termino_es','termino_es');?>
        <?php echo $this->formText('termino_es',$this->data->getTermino_es(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('termino_en','termino_en');?>
        <?php echo $this->formText('termino_en',$this->data->getTermino_en(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('link_es','link_es');?>
        <?php echo $this->formText('link_es',$this->data->getLink_es(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('link_en','link_en');?>
        <?php echo $this->formText('link_en',$this->data->getLink_en(),array('size' => 10)).'<br>';?>
               
	    <?php echo $this->formSubmit('enviar', 'enviar'); 
	 ?></FORM> 