<table style="width:600px">
<tr>
	<td></td>
	  
    <td>id</td>
          
    <td>termino_es</td>
          
    <td>termino_en</td>
          
    <td>link_es</td>
          
    <td>link_en</td>
            
</tr>	
<?php foreach($this->result AS $result):?>
	<tr>		
		<td>
			<a href="/dcc-terminos-footer/delete/id/<?php echo str_replace('_','-',$result->getId());?>">delete</a> 
			-
			<a href="/dcc-terminos-footer/edit/id/<?php echo $result->getId();?>">edit</a>
		</td>
		  
        <td><?php echo $result->getId();?></td>
          
        <td><?php echo $result->getTermino_es();?></td>
          
        <td><?php echo $result->getTermino_en();?></td>
          
        <td><?php echo $result->getLink_es();?></td>
          
        <td><?php echo $result->getLink_en();?></td>
        	</tr>
<?php endforeach?></table>

<FORM ACTION="/dcc-terminos-footer/index" METHOD="POST"> 
	 
		  
        
        <?php echo $this->formLabel('id','id');?>
        <?php echo $this->formText('id',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('termino_es','termino_es');?>
        <?php echo $this->formText('termino_es',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('termino_en','termino_en');?>
        <?php echo $this->formText('termino_en',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('link_es','link_es');?>
        <?php echo $this->formText('link_es',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('link_en','link_en');?>
        <?php echo $this->formText('link_en',' ',array('size' => 10)).'<br>';?>
               
	    <?php echo $this->formSubmit('enviar', 'enviar'); 
	 ?></FORM> 

