
<FORM ACTION="/dcc-casa/index" METHOD="POST"> 
	 
		  
        
        <?php echo $this->formLabel('id','id');?>
        <?php echo $this->formText('id',$this->data->getId(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_dcc_usuariweb','fk_dcc_usuariweb');?>
        <?php echo $this->formText('fk_dcc_usuariweb',$this->data->getFk_dcc_usuariweb(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('titol_ca','titol_ca');?>
        <?php echo $this->formText('titol_ca',$this->data->getTitol_ca(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('cpost','cpost');?>
        <?php echo $this->formText('cpost',$this->data->getCpost(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('longi','longi');?>
        <?php echo $this->formText('longi',$this->data->getLongi(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('latit','latit');?>
        <?php echo $this->formText('latit',$this->data->getLatit(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_dcc_zonab','fk_dcc_zonab');?>
        <?php echo $this->formText('fk_dcc_zonab',$this->data->getFk_dcc_zonab(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_dcc_casa_dcc_ptinteres','fk_dcc_casa_dcc_ptinteres');?>
        <?php echo $this->formText('fk_dcc_casa_dcc_ptinteres',$this->data->getFk_dcc_casa_dcc_ptinteres(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_tipusvivenda','fk_tipusvivenda');?>
        <?php echo $this->formText('fk_tipusvivenda',$this->data->getFk_tipusvivenda(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('llits_matrimoni','llits_matrimoni');?>
        <?php echo $this->formText('llits_matrimoni',$this->data->getLlits_matrimoni(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('llits_individuals','llits_individuals');?>
        <?php echo $this->formText('llits_individuals',$this->data->getLlits_individuals(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('dormitoris','dormitoris');?>
        <?php echo $this->formText('dormitoris',$this->data->getDormitoris(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('banys','banys');?>
        <?php echo $this->formText('banys',$this->data->getBanys(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('txt_ca','txt_ca');?>
        <?php echo $this->formText('txt_ca',$this->data->getTxt_ca(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_dcc_disponibilitatcasa','fk_dcc_disponibilitatcasa');?>
        <?php echo $this->formText('fk_dcc_disponibilitatcasa',$this->data->getFk_dcc_disponibilitatcasa(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_dcc_caractcasa','fk_dcc_caractcasa');?>
        <?php echo $this->formText('fk_dcc_caractcasa',$this->data->getFk_dcc_caractcasa(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_dcc_caractentorn','fk_dcc_caractentorn');?>
        <?php echo $this->formText('fk_dcc_caractentorn',$this->data->getFk_dcc_caractentorn(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('estat','estat');?>
        <?php echo $this->formText('estat',$this->data->getEstat(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('visibilitat','visibilitat');?>
        <?php echo $this->formText('visibilitat',$this->data->getVisibilitat(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('data_caducitat','data_caducitat');?>
        <?php echo $this->formText('data_caducitat',$this->data->getData_caducitat(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('pvp','pvp');?>
        <?php echo $this->formText('pvp',$this->data->getPvp(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('publicado','publicado');?>
        <?php echo $this->formText('publicado',$this->data->getPublicado(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('permalink_ca','permalink_ca');?>
        <?php echo $this->formText('permalink_ca',$this->data->getPermalink_ca(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('title_ca','title_ca');?>
        <?php echo $this->formText('title_ca',$this->data->getTitle_ca(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('keywords_ca','keywords_ca');?>
        <?php echo $this->formText('keywords_ca',$this->data->getKeywords_ca(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('description_ca','description_ca');?>
        <?php echo $this->formText('description_ca',$this->data->getDescription_ca(),array('size' => 10)).'<br>';?>
               
	    <?php echo $this->formSubmit('enviar', 'enviar'); 
	 ?></FORM> 