<table style="width:600px">
<tr>
	<td></td>
	  
    <td>id</td>
          
    <td>nombre_es</td>
          
    <td>nombre_ca</td>
          
    <td>permalink_es</td>
          
    <td>permalink_ca</td>
          
    <td>descripcion_es</td>
          
    <td>descripcion_ca</td>
          
    <td>publicada</td>
            
</tr>	
<?php foreach($this->result AS $result):?>
	<tr>		
		<td>
			<a href="/blog-tag/delete/id/<?php echo str_replace('_','-',$result->getId());?>">delete</a> 
			-
			<a href="/blog-tag/edit/id/<?php echo $result->getId();?>">edit</a>
		</td>
		  
        <td><?php echo $result->getId();?></td>
          
        <td><?php echo $result->getNombre_es();?></td>
          
        <td><?php echo $result->getNombre_ca();?></td>
          
        <td><?php echo $result->getPermalink_es();?></td>
          
        <td><?php echo $result->getPermalink_ca();?></td>
          
        <td><?php echo $result->getDescripcion_es();?></td>
          
        <td><?php echo $result->getDescripcion_ca();?></td>
          
        <td><?php echo $result->getPublicada();?></td>
        	</tr>
<?php endforeach?></table>

<FORM ACTION="/blog-tag/index" METHOD="POST"> 
	 
		  
        
        <?php echo $this->formLabel('id','id');?>
        <?php echo $this->formText('id',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('nombre_es','nombre_es');?>
        <?php echo $this->formText('nombre_es',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('nombre_ca','nombre_ca');?>
        <?php echo $this->formText('nombre_ca',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('permalink_es','permalink_es');?>
        <?php echo $this->formText('permalink_es',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('permalink_ca','permalink_ca');?>
        <?php echo $this->formText('permalink_ca',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('descripcion_es','descripcion_es');?>
        <?php echo $this->formText('descripcion_es',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('descripcion_ca','descripcion_ca');?>
        <?php echo $this->formText('descripcion_ca',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('publicada','publicada');?>
        <?php echo $this->formText('publicada',' ',array('size' => 10)).'<br>';?>
               
	    <?php echo $this->formSubmit('enviar', 'enviar'); 
	 ?></FORM> 

