
<FORM ACTION="/blog-post-dcc-ptinteres/index" METHOD="POST"> 
	 
		  
        
        <?php echo $this->formLabel('id','id');?>
        <?php echo $this->formText('id',$this->data->getId(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_blog_post','fk_blog_post');?>
        <?php echo $this->formText('fk_blog_post',$this->data->getFk_blog_post(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_dcc_ptinteres','fk_dcc_ptinteres');?>
        <?php echo $this->formText('fk_dcc_ptinteres',$this->data->getFk_dcc_ptinteres(),array('size' => 10)).'<br>';?>
               
	    <?php echo $this->formSubmit('enviar', 'enviar'); 
	 ?></FORM> 