<table style="width:600px">
<tr>
	<td></td>
	  
    <td>id</td>
          
    <td>pregunta_ca</td>
          
    <td>resposta_ca</td>
          
    <td>orden</td>
          
    <td>publicado</td>
            
</tr>	
<?php foreach($this->result AS $result):?>
	<tr>		
		<td>
			<a href="/dcc-faq/delete/id/<?php echo str_replace('_','-',$result->getId());?>">delete</a> 
			-
			<a href="/dcc-faq/edit/id/<?php echo $result->getId();?>">edit</a>
		</td>
		  
        <td><?php echo $result->getId();?></td>
          
        <td><?php echo $result->getPregunta_ca();?></td>
          
        <td><?php echo $result->getResposta_ca();?></td>
          
        <td><?php echo $result->getOrden();?></td>
          
        <td><?php echo $result->getPublicado();?></td>
        	</tr>
<?php endforeach?></table>

<FORM ACTION="/dcc-faq/index" METHOD="POST"> 
	 
		  
        
        <?php echo $this->formLabel('id','id');?>
        <?php echo $this->formText('id',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('pregunta_ca','pregunta_ca');?>
        <?php echo $this->formText('pregunta_ca',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('resposta_ca','resposta_ca');?>
        <?php echo $this->formText('resposta_ca',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('orden','orden');?>
        <?php echo $this->formText('orden',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('publicado','publicado');?>
        <?php echo $this->formText('publicado',' ',array('size' => 10)).'<br>';?>
               
	    <?php echo $this->formSubmit('enviar', 'enviar'); 
	 ?></FORM> 

