
<FORM ACTION="/dcc-casaintercanvi/index" METHOD="POST"> 
	 
		  
        
        <?php echo $this->formLabel('id','id');?>
        <?php echo $this->formText('id',$this->data->getId(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_dcc_intercanvi','fk_dcc_intercanvi');?>
        <?php echo $this->formText('fk_dcc_intercanvi',$this->data->getFk_dcc_intercanvi(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_dcc_casa','fk_dcc_casa');?>
        <?php echo $this->formText('fk_dcc_casa',$this->data->getFk_dcc_casa(),array('size' => 10)).'<br>';?>
               
	    <?php echo $this->formSubmit('enviar', 'enviar'); 
	 ?></FORM> 