
<FORM ACTION="/dcc-imagenescasa/index" METHOD="POST"> 
	 
		  
        
        <?php echo $this->formLabel('id','id');?>
        <?php echo $this->formText('id',$this->data->getId(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_dcc_casa','fk_dcc_casa');?>
        <?php echo $this->formText('fk_dcc_casa',$this->data->getFk_dcc_casa(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('titol_ca','titol_ca');?>
        <?php echo $this->formText('titol_ca',$this->data->getTitol_ca(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('txt_ca','txt_ca');?>
        <?php echo $this->formText('txt_ca',$this->data->getTxt_ca(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('file','file');?>
        <?php echo $this->formText('file',$this->data->getFile(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('orden','orden');?>
        <?php echo $this->formText('orden',$this->data->getOrden(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('tipo','tipo');?>
        <?php echo $this->formText('tipo',$this->data->getTipo(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('cod','cod');?>
        <?php echo $this->formText('cod',$this->data->getCod(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('publicado','publicado');?>
        <?php echo $this->formText('publicado',$this->data->getPublicado(),array('size' => 10)).'<br>';?>
               
	    <?php echo $this->formSubmit('enviar', 'enviar'); 
	 ?></FORM> 