<table style="width:600px">
<tr>
	<td></td>
	  
    <td>id</td>
          
    <td>fk_dcc_casa</td>
          
    <td>fk_dcc_caractentorn</td>
            
</tr>	
<?php foreach($this->result AS $result):?>
	<tr>		
		<td>
			<a href="/dcc-casa-dcc-caractentorn/delete/id/<?php echo str_replace('_','-',$result->getId());?>">delete</a> 
			-
			<a href="/dcc-casa-dcc-caractentorn/edit/id/<?php echo $result->getId();?>">edit</a>
		</td>
		  
        <td><?php echo $result->getId();?></td>
          
        <td><?php echo $result->getFk_dcc_casa();?></td>
          
        <td><?php echo $result->getFk_dcc_caractentorn();?></td>
        	</tr>
<?php endforeach?></table>

<FORM ACTION="/dcc-casa-dcc-caractentorn/index" METHOD="POST"> 
	 
		  
        
        <?php echo $this->formLabel('id','id');?>
        <?php echo $this->formText('id',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_dcc_casa','fk_dcc_casa');?>
        <?php echo $this->formText('fk_dcc_casa',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_dcc_caractentorn','fk_dcc_caractentorn');?>
        <?php echo $this->formText('fk_dcc_caractentorn',' ',array('size' => 10)).'<br>';?>
               
	    <?php echo $this->formSubmit('enviar', 'enviar'); 
	 ?></FORM> 

