<table style="width:600px">
<tr>
	<td></td>
	  
    <td>id</td>
          
    <td>fk_blog_post</td>
          
    <td>fk_blog_category</td>
            
</tr>	
<?php foreach($this->result AS $result):?>
	<tr>		
		<td>
			<a href="/blog-post-blog-category/delete/id/<?php echo str_replace('_','-',$result->getId());?>">delete</a> 
			-
			<a href="/blog-post-blog-category/edit/id/<?php echo $result->getId();?>">edit</a>
		</td>
		  
        <td><?php echo $result->getId();?></td>
          
        <td><?php echo $result->getFk_blog_post();?></td>
          
        <td><?php echo $result->getFk_blog_category();?></td>
        	</tr>
<?php endforeach?></table>

<FORM ACTION="/blog-post-blog-category/index" METHOD="POST"> 
	 
		  
        
        <?php echo $this->formLabel('id','id');?>
        <?php echo $this->formText('id',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_blog_post','fk_blog_post');?>
        <?php echo $this->formText('fk_blog_post',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_blog_category','fk_blog_category');?>
        <?php echo $this->formText('fk_blog_category',' ',array('size' => 10)).'<br>';?>
               
	    <?php echo $this->formSubmit('enviar', 'enviar'); 
	 ?></FORM> 

