
<FORM ACTION="/dcc-ptinteres-dcc-ptcategories/index" METHOD="POST"> 
	 
		  
        
        <?php echo $this->formLabel('id','id');?>
        <?php echo $this->formText('id',$this->data->getId(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_dcc_ptinteres','fk_dcc_ptinteres');?>
        <?php echo $this->formText('fk_dcc_ptinteres',$this->data->getFk_dcc_ptinteres(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_dcc_ptcategories','fk_dcc_ptcategories');?>
        <?php echo $this->formText('fk_dcc_ptcategories',$this->data->getFk_dcc_ptcategories(),array('size' => 10)).'<br>';?>
               
	    <?php echo $this->formSubmit('enviar', 'enviar'); 
	 ?></FORM> 