<table style="width:600px">
<tr>
	<td></td>
	  
    <td>id</td>
          
    <td>fk_dcc_ptinteres</td>
          
    <td>fk_dcc_ptcategories</td>
            
</tr>	
<?php foreach($this->result AS $result):?>
	<tr>		
		<td>
			<a href="/dcc-ptinteres-dcc-ptcategories/delete/id/<?php echo str_replace('_','-',$result->getId());?>">delete</a> 
			-
			<a href="/dcc-ptinteres-dcc-ptcategories/edit/id/<?php echo $result->getId();?>">edit</a>
		</td>
		  
        <td><?php echo $result->getId();?></td>
          
        <td><?php echo $result->getFk_dcc_ptinteres();?></td>
          
        <td><?php echo $result->getFk_dcc_ptcategories();?></td>
        	</tr>
<?php endforeach?></table>

<FORM ACTION="/dcc-ptinteres-dcc-ptcategories/index" METHOD="POST"> 
	 
		  
        
        <?php echo $this->formLabel('id','id');?>
        <?php echo $this->formText('id',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_dcc_ptinteres','fk_dcc_ptinteres');?>
        <?php echo $this->formText('fk_dcc_ptinteres',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_dcc_ptcategories','fk_dcc_ptcategories');?>
        <?php echo $this->formText('fk_dcc_ptcategories',' ',array('size' => 10)).'<br>';?>
               
	    <?php echo $this->formSubmit('enviar', 'enviar'); 
	 ?></FORM> 

