<table style="width:600px">
<tr>
	<td></td>
	  
    <td>id</td>
          
    <td>fk_usuariweb</td>
          
    <td>fkcasa</td>
            
</tr>	
<?php foreach($this->result AS $result):?>
	<tr>		
		<td>
			<a href="/dcc-meinteresa/delete/id/<?php echo str_replace('_','-',$result->getId());?>">delete</a> 
			-
			<a href="/dcc-meinteresa/edit/id/<?php echo $result->getId();?>">edit</a>
		</td>
		  
        <td><?php echo $result->getId();?></td>
          
        <td><?php echo $result->getFk_usuariweb();?></td>
          
        <td><?php echo $result->getFkcasa();?></td>
        	</tr>
<?php endforeach?></table>

<FORM ACTION="/dcc-meinteresa/index" METHOD="POST"> 
	 
		  
        
        <?php echo $this->formLabel('id','id');?>
        <?php echo $this->formText('id',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_usuariweb','fk_usuariweb');?>
        <?php echo $this->formText('fk_usuariweb',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fkcasa','fkcasa');?>
        <?php echo $this->formText('fkcasa',' ',array('size' => 10)).'<br>';?>
               
	    <?php echo $this->formSubmit('enviar', 'enviar'); 
	 ?></FORM> 

