<table style="width:600px">
<tr>
	<td></td>
	  
    <td>id</td>
          
    <td>nom</td>
          
    <td>mail</td>
          
    <td>passwd</td>
          
    <td>state</td>
          
    <td>time</td>
          
    <td>documento</td>
          
    <td>persones</td>
          
    <td>info</td>
          
    <td>imatge</td>
          
    <td>idioma</td>
          
    <td>poblacion</td>
          
    <td>activo</td>
          
    <td>permalink</td>
          
    <td>title_ca</td>
          
    <td>keywords_ca</td>
          
    <td>description_ca</td>
            
</tr>	
<?php foreach($this->result AS $result):?>
	<tr>		
		<td>
			<a href="/dcc-usuariweb/delete/id/<?php echo str_replace('_','-',$result->getId());?>">delete</a> 
			-
			<a href="/dcc-usuariweb/edit/id/<?php echo $result->getId();?>">edit</a>
		</td>
		  
        <td><?php echo $result->getId();?></td>
          
        <td><?php echo $result->getNom();?></td>
          
        <td><?php echo $result->getMail();?></td>
          
        <td><?php echo $result->getPasswd();?></td>
          
        <td><?php echo $result->getState();?></td>
          
        <td><?php echo $result->getTime();?></td>
          
        <td><?php echo $result->getDocumento();?></td>
          
        <td><?php echo $result->getPersones();?></td>
          
        <td><?php echo $result->getInfo();?></td>
          
        <td><?php echo $result->getImatge();?></td>
          
        <td><?php echo $result->getIdioma();?></td>
          
        <td><?php echo $result->getPoblacion();?></td>
          
        <td><?php echo $result->getActivo();?></td>
          
        <td><?php echo $result->getPermalink();?></td>
          
        <td><?php echo $result->getTitle_ca();?></td>
          
        <td><?php echo $result->getKeywords_ca();?></td>
          
        <td><?php echo $result->getDescription_ca();?></td>
        	</tr>
<?php endforeach?></table>

<FORM ACTION="/dcc-usuariweb/index" METHOD="POST"> 
	 
		  
        
        <?php echo $this->formLabel('id','id');?>
        <?php echo $this->formText('id',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('nom','nom');?>
        <?php echo $this->formText('nom',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('mail','mail');?>
        <?php echo $this->formText('mail',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('passwd','passwd');?>
        <?php echo $this->formText('passwd',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('state','state');?>
        <?php echo $this->formText('state',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('time','time');?>
        <?php echo $this->formText('time',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('documento','documento');?>
        <?php echo $this->formText('documento',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('persones','persones');?>
        <?php echo $this->formText('persones',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('info','info');?>
        <?php echo $this->formText('info',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('imatge','imatge');?>
        <?php echo $this->formText('imatge',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('idioma','idioma');?>
        <?php echo $this->formText('idioma',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('poblacion','poblacion');?>
        <?php echo $this->formText('poblacion',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('activo','activo');?>
        <?php echo $this->formText('activo',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('permalink','permalink');?>
        <?php echo $this->formText('permalink',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('title_ca','title_ca');?>
        <?php echo $this->formText('title_ca',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('keywords_ca','keywords_ca');?>
        <?php echo $this->formText('keywords_ca',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('description_ca','description_ca');?>
        <?php echo $this->formText('description_ca',' ',array('size' => 10)).'<br>';?>
               
	    <?php echo $this->formSubmit('enviar', 'enviar'); 
	 ?></FORM> 

