
<FORM ACTION="/dcc-usuariweb-dcc-zonac/index" METHOD="POST"> 
	 
		  
        
        <?php echo $this->formLabel('id','id');?>
        <?php echo $this->formText('id',$this->data->getId(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_dcc_usuariweb','fk_dcc_usuariweb');?>
        <?php echo $this->formText('fk_dcc_usuariweb',$this->data->getFk_dcc_usuariweb(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_zonac','fk_zonac');?>
        <?php echo $this->formText('fk_zonac',$this->data->getFk_zonac(),array('size' => 10)).'<br>';?>
               
	    <?php echo $this->formSubmit('enviar', 'enviar'); 
	 ?></FORM> 