<table style="width:600px">
<tr>
	<td></td>
	  
    <td>id</td>
          
    <td>fk_dcc_usuariweb</td>
          
    <td>fk_zonac</td>
            
</tr>	
<?php foreach($this->result AS $result):?>
	<tr>		
		<td>
			<a href="/dcc-usuariweb-dcc-zonac/delete/id/<?php echo str_replace('_','-',$result->getId());?>">delete</a> 
			-
			<a href="/dcc-usuariweb-dcc-zonac/edit/id/<?php echo $result->getId();?>">edit</a>
		</td>
		  
        <td><?php echo $result->getId();?></td>
          
        <td><?php echo $result->getFk_dcc_usuariweb();?></td>
          
        <td><?php echo $result->getFk_zonac();?></td>
        	</tr>
<?php endforeach?></table>

<FORM ACTION="/dcc-usuariweb-dcc-zonac/index" METHOD="POST"> 
	 
		  
        
        <?php echo $this->formLabel('id','id');?>
        <?php echo $this->formText('id',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_dcc_usuariweb','fk_dcc_usuariweb');?>
        <?php echo $this->formText('fk_dcc_usuariweb',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_zonac','fk_zonac');?>
        <?php echo $this->formText('fk_zonac',' ',array('size' => 10)).'<br>';?>
               
	    <?php echo $this->formSubmit('enviar', 'enviar'); 
	 ?></FORM> 

