<table style="width:600px">
<tr>
	<td></td>
	  
    <td>id</td>
          
    <td>url</td>
          
    <td>alias</td>
          
    <td>fk_usuario</td>
          
    <td>variables</td>
            
</tr>	
<?php foreach($this->result AS $result):?>
	<tr>		
		<td>
			<a href="/dcc-favoritos/delete/id/<?php echo str_replace('_','-',$result->getId());?>">delete</a> 
			-
			<a href="/dcc-favoritos/edit/id/<?php echo $result->getId();?>">edit</a>
		</td>
		  
        <td><?php echo $result->getId();?></td>
          
        <td><?php echo $result->getUrl();?></td>
          
        <td><?php echo $result->getAlias();?></td>
          
        <td><?php echo $result->getFk_usuario();?></td>
          
        <td><?php echo $result->getVariables();?></td>
        	</tr>
<?php endforeach?></table>

<FORM ACTION="/dcc-favoritos/index" METHOD="POST"> 
	 
		  
        
        <?php echo $this->formLabel('id','id');?>
        <?php echo $this->formText('id',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('url','url');?>
        <?php echo $this->formText('url',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('alias','alias');?>
        <?php echo $this->formText('alias',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_usuario','fk_usuario');?>
        <?php echo $this->formText('fk_usuario',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('variables','variables');?>
        <?php echo $this->formText('variables',' ',array('size' => 10)).'<br>';?>
               
	    <?php echo $this->formSubmit('enviar', 'enviar'); 
	 ?></FORM> 

