
<FORM ACTION="/dcc-intercanvi/index" METHOD="POST"> 
	 
		  
        
        <?php echo $this->formLabel('id','id');?>
        <?php echo $this->formText('id',$this->data->getId(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_dcc_valoraciointercanvi','fk_dcc_valoraciointercanvi');?>
        <?php echo $this->formText('fk_dcc_valoraciointercanvi',$this->data->getFk_dcc_valoraciointercanvi(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_casa_tria','fk_casa_tria');?>
        <?php echo $this->formText('fk_casa_tria',$this->data->getFk_casa_tria(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_dcc_casaintercanvi','fk_dcc_casaintercanvi');?>
        <?php echo $this->formText('fk_dcc_casaintercanvi',$this->data->getFk_dcc_casaintercanvi(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_usuariweb_a','fk_usuariweb_a');?>
        <?php echo $this->formText('fk_usuariweb_a',$this->data->getFk_usuariweb_a(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_usuariweb_b','fk_usuariweb_b');?>
        <?php echo $this->formText('fk_usuariweb_b',$this->data->getFk_usuariweb_b(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('data_ini','data_ini');?>
        <?php echo $this->formText('data_ini',$this->data->getData_ini(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('data_fin','data_fin');?>
        <?php echo $this->formText('data_fin',$this->data->getData_fin(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('data_proposta','data_proposta');?>
        <?php echo $this->formText('data_proposta',$this->data->getData_proposta(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('comentario','comentario');?>
        <?php echo $this->formText('comentario',$this->data->getComentario(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('publicado','publicado');?>
        <?php echo $this->formText('publicado',$this->data->getPublicado(),array('size' => 10)).'<br>';?>
               
	    <?php echo $this->formSubmit('enviar', 'enviar'); 
	 ?></FORM> 