
<FORM ACTION="/dcc-comentarios/index" METHOD="POST"> 
	 
		  
        
        <?php echo $this->formLabel('id','id');?>
        <?php echo $this->formText('id',$this->data->getId(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_usuariweb','fk_usuariweb');?>
        <?php echo $this->formText('fk_usuariweb',$this->data->getFk_usuariweb(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_parent_comentario','fk_parent_comentario');?>
        <?php echo $this->formText('fk_parent_comentario',$this->data->getFk_parent_comentario(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_dcc_intercambio','fk_dcc_intercambio');?>
        <?php echo $this->formText('fk_dcc_intercambio',$this->data->getFk_dcc_intercambio(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('texto','texto');?>
        <?php echo $this->formText('texto',$this->data->getTexto(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fecha','fecha');?>
        <?php echo $this->formText('fecha',$this->data->getFecha(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('publicado','publicado');?>
        <?php echo $this->formText('publicado',$this->data->getPublicado(),array('size' => 10)).'<br>';?>
               
	    <?php echo $this->formSubmit('enviar', 'enviar'); 
	 ?></FORM> 