<table style="width:600px">
<tr>
	<td></td>
	  
    <td>id</td>
          
    <td>fk_usuariweb</td>
          
    <td>fk_parent_comentario</td>
          
    <td>fk_dcc_intercambio</td>
          
    <td>texto</td>
          
    <td>fecha</td>
          
    <td>publicado</td>
            
</tr>	
<?php foreach($this->result AS $result):?>
	<tr>		
		<td>
			<a href="/dcc-comentarios/delete/id/<?php echo str_replace('_','-',$result->getId());?>">delete</a> 
			-
			<a href="/dcc-comentarios/edit/id/<?php echo $result->getId();?>">edit</a>
		</td>
		  
        <td><?php echo $result->getId();?></td>
          
        <td><?php echo $result->getFk_usuariweb();?></td>
          
        <td><?php echo $result->getFk_parent_comentario();?></td>
          
        <td><?php echo $result->getFk_dcc_intercambio();?></td>
          
        <td><?php echo $result->getTexto();?></td>
          
        <td><?php echo $result->getFecha();?></td>
          
        <td><?php echo $result->getPublicado();?></td>
        	</tr>
<?php endforeach?></table>

<FORM ACTION="/dcc-comentarios/index" METHOD="POST"> 
	 
		  
        
        <?php echo $this->formLabel('id','id');?>
        <?php echo $this->formText('id',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_usuariweb','fk_usuariweb');?>
        <?php echo $this->formText('fk_usuariweb',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_parent_comentario','fk_parent_comentario');?>
        <?php echo $this->formText('fk_parent_comentario',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_dcc_intercambio','fk_dcc_intercambio');?>
        <?php echo $this->formText('fk_dcc_intercambio',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('texto','texto');?>
        <?php echo $this->formText('texto',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fecha','fecha');?>
        <?php echo $this->formText('fecha',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('publicado','publicado');?>
        <?php echo $this->formText('publicado',' ',array('size' => 10)).'<br>';?>
               
	    <?php echo $this->formSubmit('enviar', 'enviar'); 
	 ?></FORM> 

