
<FORM ACTION="/dcc-ptinteres/index" METHOD="POST"> 
	 
		  
        
        <?php echo $this->formLabel('id','id');?>
        <?php echo $this->formText('id',$this->data->getId(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('nombre_es','nombre_es');?>
        <?php echo $this->formText('nombre_es',$this->data->getNombre_es(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('nombre_ca','nombre_ca');?>
        <?php echo $this->formText('nombre_ca',$this->data->getNombre_ca(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_zonab','fk_zonab');?>
        <?php echo $this->formText('fk_zonab',$this->data->getFk_zonab(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('dcc_ptinteres_dcc_ptcategories','dcc_ptinteres_dcc_ptcategories');?>
        <?php echo $this->formText('dcc_ptinteres_dcc_ptcategories',$this->data->getDcc_ptinteres_dcc_ptcategories(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('permalink_es','permalink_es');?>
        <?php echo $this->formText('permalink_es',$this->data->getPermalink_es(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('permalink_ca','permalink_ca');?>
        <?php echo $this->formText('permalink_ca',$this->data->getPermalink_ca(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('publicado','publicado');?>
        <?php echo $this->formText('publicado',$this->data->getPublicado(),array('size' => 10)).'<br>';?>
               
	    <?php echo $this->formSubmit('enviar', 'enviar'); 
	 ?></FORM> 