<table style="width:600px">
<tr>
	<td></td>
	  
    <td>id</td>
          
    <td>nombre_es</td>
          
    <td>nombre_ca</td>
          
    <td>fk_zonab</td>
          
    <td>dcc_ptinteres_dcc_ptcategories</td>
          
    <td>permalink_es</td>
          
    <td>permalink_ca</td>
          
    <td>publicado</td>
            
</tr>	
<?php foreach($this->result AS $result):?>
	<tr>		
		<td>
			<a href="/dcc-ptinteres/delete/id/<?php echo str_replace('_','-',$result->getId());?>">delete</a> 
			-
			<a href="/dcc-ptinteres/edit/id/<?php echo $result->getId();?>">edit</a>
		</td>
		  
        <td><?php echo $result->getId();?></td>
          
        <td><?php echo $result->getNombre_es();?></td>
          
        <td><?php echo $result->getNombre_ca();?></td>
          
        <td><?php echo $result->getFk_zonab();?></td>
          
        <td><?php echo $result->getDcc_ptinteres_dcc_ptcategories();?></td>
          
        <td><?php echo $result->getPermalink_es();?></td>
          
        <td><?php echo $result->getPermalink_ca();?></td>
          
        <td><?php echo $result->getPublicado();?></td>
        	</tr>
<?php endforeach?></table>

<FORM ACTION="/dcc-ptinteres/index" METHOD="POST"> 
	 
		  
        
        <?php echo $this->formLabel('id','id');?>
        <?php echo $this->formText('id',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('nombre_es','nombre_es');?>
        <?php echo $this->formText('nombre_es',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('nombre_ca','nombre_ca');?>
        <?php echo $this->formText('nombre_ca',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_zonab','fk_zonab');?>
        <?php echo $this->formText('fk_zonab',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('dcc_ptinteres_dcc_ptcategories','dcc_ptinteres_dcc_ptcategories');?>
        <?php echo $this->formText('dcc_ptinteres_dcc_ptcategories',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('permalink_es','permalink_es');?>
        <?php echo $this->formText('permalink_es',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('permalink_ca','permalink_ca');?>
        <?php echo $this->formText('permalink_ca',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('publicado','publicado');?>
        <?php echo $this->formText('publicado',' ',array('size' => 10)).'<br>';?>
               
	    <?php echo $this->formSubmit('enviar', 'enviar'); 
	 ?></FORM> 

