
<FORM ACTION="/blog-coments/index" METHOD="POST"> 
	 
		  
        
        <?php echo $this->formLabel('id','id');?>
        <?php echo $this->formText('id',$this->data->getId(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('nombre','nombre');?>
        <?php echo $this->formText('nombre',$this->data->getNombre(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_blog_user','fk_blog_user');?>
        <?php echo $this->formText('fk_blog_user',$this->data->getFk_blog_user(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('email','email');?>
        <?php echo $this->formText('email',$this->data->getEmail(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('url','url');?>
        <?php echo $this->formText('url',$this->data->getUrl(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('comentario','comentario');?>
        <?php echo $this->formText('comentario',$this->data->getComentario(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fecha','fecha');?>
        <?php echo $this->formText('fecha',$this->data->getFecha(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_blog_post','fk_blog_post');?>
        <?php echo $this->formText('fk_blog_post',$this->data->getFk_blog_post(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('publicado','publicado');?>
        <?php echo $this->formText('publicado',$this->data->getPublicado(),array('size' => 10)).'<br>';?>
               
	    <?php echo $this->formSubmit('enviar', 'enviar'); 
	 ?></FORM> 