
<FORM ACTION="/dcc-usuari/index" METHOD="POST"> 
	 
		  
        
        <?php echo $this->formLabel('id','id');?>
        <?php echo $this->formText('id',$this->data->getId(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('nombre','nombre');?>
        <?php echo $this->formText('nombre',$this->data->getNombre(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('usuario','usuario');?>
        <?php echo $this->formText('usuario',$this->data->getUsuario(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('passwd','passwd');?>
        <?php echo $this->formText('passwd',$this->data->getPasswd(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('email','email');?>
        <?php echo $this->formText('email',$this->data->getEmail(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('perfils','perfils');?>
        <?php echo $this->formText('perfils',$this->data->getPerfils(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('perfil','perfil');?>
        <?php echo $this->formText('perfil',$this->data->getPerfil(),array('size' => 10)).'<br>';?>
               
	    <?php echo $this->formSubmit('enviar', 'enviar'); 
	 ?></FORM> 