<table style="width:600px">
<tr>
	<td></td>
	  
    <td>id</td>
          
    <td>nombre_es</td>
          
    <td>nombre_ca</td>
          
    <td>fk_zonac</td>
          
    <td>publicado</td>
            
</tr>	
<?php foreach($this->result AS $result):?>
	<tr>		
		<td>
			<a href="/dcc-zonab/delete/id/<?php echo str_replace('_','-',$result->getId());?>">delete</a> 
			-
			<a href="/dcc-zonab/edit/id/<?php echo $result->getId();?>">edit</a>
		</td>
		  
        <td><?php echo $result->getId();?></td>
          
        <td><?php echo $result->getNombre_es();?></td>
          
        <td><?php echo $result->getNombre_ca();?></td>
          
        <td><?php echo $result->getFk_zonac();?></td>
          
        <td><?php echo $result->getPublicado();?></td>
        	</tr>
<?php endforeach?></table>

<FORM ACTION="/dcc-zonab/index" METHOD="POST"> 
	 
		  
        
        <?php echo $this->formLabel('id','id');?>
        <?php echo $this->formText('id',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('nombre_es','nombre_es');?>
        <?php echo $this->formText('nombre_es',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('nombre_ca','nombre_ca');?>
        <?php echo $this->formText('nombre_ca',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_zonac','fk_zonac');?>
        <?php echo $this->formText('fk_zonac',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('publicado','publicado');?>
        <?php echo $this->formText('publicado',' ',array('size' => 10)).'<br>';?>
               
	    <?php echo $this->formSubmit('enviar', 'enviar'); 
	 ?></FORM> 

