
<FORM ACTION="/dcc-valoraciointercanvi/index" METHOD="POST"> 
	 
		  
        
        <?php echo $this->formLabel('id','id');?>
        <?php echo $this->formText('id',$this->data->getId(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_dcc_casa','fk_dcc_casa');?>
        <?php echo $this->formText('fk_dcc_casa',$this->data->getFk_dcc_casa(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_dcc_usuariweb','fk_dcc_usuariweb');?>
        <?php echo $this->formText('fk_dcc_usuariweb',$this->data->getFk_dcc_usuariweb(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('text','text');?>
        <?php echo $this->formText('text',$this->data->getText(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('valoracio','valoracio');?>
        <?php echo $this->formText('valoracio',$this->data->getValoracio(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('data','data');?>
        <?php echo $this->formText('data',$this->data->getData(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('publicado','publicado');?>
        <?php echo $this->formText('publicado',$this->data->getPublicado(),array('size' => 10)).'<br>';?>
               
	    <?php echo $this->formSubmit('enviar', 'enviar'); 
	 ?></FORM> 