
<FORM ACTION="/dcc-tarifes/index" METHOD="POST"> 
	 
		  
        
        <?php echo $this->formLabel('id','id');?>
        <?php echo $this->formText('id',$this->data->getId(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('titol_ca','titol_ca');?>
        <?php echo $this->formText('titol_ca',$this->data->getTitol_ca(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('text_ca','text_ca');?>
        <?php echo $this->formText('text_ca',$this->data->getText_ca(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('publicado','publicado');?>
        <?php echo $this->formText('publicado',$this->data->getPublicado(),array('size' => 10)).'<br>';?>
               
	    <?php echo $this->formSubmit('enviar', 'enviar'); 
	 ?></FORM> 