
<FORM ACTION="/dcc-casa-dcc-ptinteres/index" METHOD="POST"> 
	 
		  
        
        <?php echo $this->formLabel('id','id');?>
        <?php echo $this->formText('id',$this->data->getId(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_dcc_casa','fk_dcc_casa');?>
        <?php echo $this->formText('fk_dcc_casa',$this->data->getFk_dcc_casa(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_dcc_ptinteres','fk_dcc_ptinteres');?>
        <?php echo $this->formText('fk_dcc_ptinteres',$this->data->getFk_dcc_ptinteres(),array('size' => 10)).'<br>';?>
               
	    <?php echo $this->formSubmit('enviar', 'enviar'); 
	 ?></FORM> 