
<FORM ACTION="/blog-post/index" METHOD="POST"> 
	 
		  
        
        <?php echo $this->formLabel('id','id');?>
        <?php echo $this->formText('id',$this->data->getId(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('titulo_es','titulo_es');?>
        <?php echo $this->formText('titulo_es',$this->data->getTitulo_es(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('titulo_ca','titulo_ca');?>
        <?php echo $this->formText('titulo_ca',$this->data->getTitulo_ca(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('permalink_es','permalink_es');?>
        <?php echo $this->formText('permalink_es',$this->data->getPermalink_es(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('permalink_ca','permalink_ca');?>
        <?php echo $this->formText('permalink_ca',$this->data->getPermalink_ca(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('foto','foto');?>
        <?php echo $this->formText('foto',$this->data->getFoto(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('foto1','foto1');?>
        <?php echo $this->formText('foto1',$this->data->getFoto1(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('foto2','foto2');?>
        <?php echo $this->formText('foto2',$this->data->getFoto2(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('foto3','foto3');?>
        <?php echo $this->formText('foto3',$this->data->getFoto3(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('foto4','foto4');?>
        <?php echo $this->formText('foto4',$this->data->getFoto4(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('texto_es','texto_es');?>
        <?php echo $this->formText('texto_es',$this->data->getTexto_es(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('texto_ca','texto_ca');?>
        <?php echo $this->formText('texto_ca',$this->data->getTexto_ca(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('blog_post_blog_category','blog_post_blog_category');?>
        <?php echo $this->formText('blog_post_blog_category',$this->data->getBlog_post_blog_category(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('video','video');?>
        <?php echo $this->formText('video',$this->data->getVideo(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('mascontenido_es','mascontenido_es');?>
        <?php echo $this->formText('mascontenido_es',$this->data->getMascontenido_es(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('mascontenido_ca','mascontenido_ca');?>
        <?php echo $this->formText('mascontenido_ca',$this->data->getMascontenido_ca(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_dcc_casa','fk_dcc_casa');?>
        <?php echo $this->formText('fk_dcc_casa',$this->data->getFk_dcc_casa(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('blog_post_dcc_ptinteres','blog_post_dcc_ptinteres');?>
        <?php echo $this->formText('blog_post_dcc_ptinteres',$this->data->getBlog_post_dcc_ptinteres(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fk_blog_user','fk_blog_user');?>
        <?php echo $this->formText('fk_blog_user',$this->data->getFk_blog_user(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('destacado','destacado');?>
        <?php echo $this->formText('destacado',$this->data->getDestacado(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('publicado','publicado');?>
        <?php echo $this->formText('publicado',$this->data->getPublicado(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('blog_post_blog_tag','blog_post_blog_tag');?>
        <?php echo $this->formText('blog_post_blog_tag',$this->data->getBlog_post_blog_tag(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('permitir_comentarios','permitir_comentarios');?>
        <?php echo $this->formText('permitir_comentarios',$this->data->getPermitir_comentarios(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('numero_comentarios','numero_comentarios');?>
        <?php echo $this->formText('numero_comentarios',$this->data->getNumero_comentarios(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('votos','votos');?>
        <?php echo $this->formText('votos',$this->data->getVotos(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fecha','fecha');?>
        <?php echo $this->formText('fecha',$this->data->getFecha(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('keywords_es','keywords_es');?>
        <?php echo $this->formText('keywords_es',$this->data->getKeywords_es(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('keywords_ca','keywords_ca');?>
        <?php echo $this->formText('keywords_ca',$this->data->getKeywords_ca(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('description_es','description_es');?>
        <?php echo $this->formText('description_es',$this->data->getDescription_es(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('description_ca','description_ca');?>
        <?php echo $this->formText('description_ca',$this->data->getDescription_ca(),array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('fecha_actualizacion','fecha_actualizacion');?>
        <?php echo $this->formText('fecha_actualizacion',$this->data->getFecha_actualizacion(),array('size' => 10)).'<br>';?>
               
	    <?php echo $this->formSubmit('enviar', 'enviar'); 
	 ?></FORM> 