<table style="width:600px">
<tr>
	<td></td>
	  
    <td>id</td>
          
    <td>nombre</td>
          
    <td>url</td>
          
    <td>descripcion_es</td>
          
    <td>descripcion_ca</td>
          
    <td>publicada</td>
          
    <td>orden</td>
            
</tr>	
<?php foreach($this->result AS $result):?>
	<tr>		
		<td>
			<a href="/blog-roll/delete/id/<?php echo str_replace('_','-',$result->getId());?>">delete</a> 
			-
			<a href="/blog-roll/edit/id/<?php echo $result->getId();?>">edit</a>
		</td>
		  
        <td><?php echo $result->getId();?></td>
          
        <td><?php echo $result->getNombre();?></td>
          
        <td><?php echo $result->getUrl();?></td>
          
        <td><?php echo $result->getDescripcion_es();?></td>
          
        <td><?php echo $result->getDescripcion_ca();?></td>
          
        <td><?php echo $result->getPublicada();?></td>
          
        <td><?php echo $result->getOrden();?></td>
        	</tr>
<?php endforeach?></table>

<FORM ACTION="/blog-roll/index" METHOD="POST"> 
	 
		  
        
        <?php echo $this->formLabel('id','id');?>
        <?php echo $this->formText('id',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('nombre','nombre');?>
        <?php echo $this->formText('nombre',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('url','url');?>
        <?php echo $this->formText('url',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('descripcion_es','descripcion_es');?>
        <?php echo $this->formText('descripcion_es',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('descripcion_ca','descripcion_ca');?>
        <?php echo $this->formText('descripcion_ca',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('publicada','publicada');?>
        <?php echo $this->formText('publicada',' ',array('size' => 10)).'<br>';?>
          
        
        <?php echo $this->formLabel('orden','orden');?>
        <?php echo $this->formText('orden',' ',array('size' => 10)).'<br>';?>
               
	    <?php echo $this->formSubmit('enviar', 'enviar'); 
	 ?></FORM> 

